# Key Binding {{{1
unbind C-b
set-option -g prefix C-t
if 'test -x pbcopy' 'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel pbcopy'

# Global Settings {{{1
set-option -g mode-keys vi
set-option -g set-titles off
set-option -g status-position bottom

set-option -g @continuum-restore on
set-option -g @continuum-save-interval '60'
set-option -g @themepack 'powerline/block/blue'
set-option -g automatic-rename on

# Plugins {{{1
set-option -g @plugin 'jimeh/tmux-themepack'
set-option -g @plugin 'tmux-plugins/tmux-resurrect'
set-option -g @plugin 'tmux-plugins/tmux-continuum'
set-option -g @plugin 'tmux-plugins/tmux-pain-control'
set-option -g @plugin 'tmux-plugins/tmux-sensible'
set-option -g @plugin 'tmux-plugins/tmux-yank'
set-option -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'
