#!/bin/bash

set -eu

basedir=$(dirname $0)
test -r $basedir/scripts/subr.sh && source $basedir/scripts/subr.sh

pushd $basedir >/dev/null 2>&1

function symlink {
    src=$(pwd)/$1
    dst=~/$1

    if [ -e $dst ]; then
        bkdir=~/backups.$(date +%Y%m%d-%H%M%S)
        mkdir -p $bkdir
        mv -f $dst $bkdir
    fi

    mkdir -p $(dirname $dst)
    ln -fs $src $dst
}

symlink .config/coc/ultisnips/all.snippets
symlink .pip/pip.conf
symlink .ssh/aws-keypair-1.pem
symlink .ssh/config
symlink .ssh/github-keypair-1.pem
symlink .vim/coc-install.vim
symlink .vim/coc-settings.json
symlink .vim/gvimrc
symlink .vim/vimrc
symlink .zsh/.zprofile
symlink .zsh/.zshrc
symlink .bash_profile
symlink .bashrc
symlink .ctags
symlink .curlrc
symlink .gitconfig
symlink .gitignore.global
symlink .inputrc
symlink .npmrc
symlink .profile
symlink .tigrc
symlink .tmux.conf
symlink .wgetrc
symlink .zshenv

if [ $(uname) = Darwin ]; then
    read -p 'Do you want to install the Homebrew packages? [Y/n]: ' -a ans
    if checkyesno ${ans:-y}; then
        $basedir/scripts/homebrew install
    fi
fi

source $basedir/.profile

if type npm >/dev/null 2>&1; then
    read -p 'Do you wanto to install the Node.js packages? [Y/n]: ' -a ans
    if checkyesno ${ans:-y}; then
        $basedir/scripts/nodejs install
    fi
fi

if type python >/dev/null 2>&1 || type python3 >/dev/null 2>&1; then
    read -p 'Do you want to install the Python packages? [Y/n]: ' -a ans
    if checkyesno ${ans:-y}; then
        $basedir/scripts/python install
    fi
fi

if type tmux >/dev/null 2>&1; then
    read -p 'Do you want to install the tmux packages? [Y/n]: ' -a ans
    if checkyesno ${ans:-y}; then
        $basedir/scripts/tmux install
    fi
fi

popd >/dev/null 2>&1
