scriptencoding utf-8

if has('win32')
  set guifont=Hack_Nerd_Font_Mono:h12,Consolas:h12
  set guifontwide=MS_Gothic:h12
  set renderoptions=type:directx
elseif has('gui_gtk')
  set guifont=Hack\ Nerd\ Font\ Mono\ 11,Monospace\ 11
elseif has('osx')
  set guifont=Hack\ Nerd\ Font\ Mono:h13,Menlo:h13
  set guifontwide=YuGo-Medium:h13
  set linespace=1
endif

set columns=160
set lines=50

source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
