scriptversion 4
syntax enable
filetype plugin indent on

let g:loaded_2html_plugin = 1
let g:loaded_getscriptPlugin = 1
let g:loaded_logiPat = 1
let g:loaded_manpager_plugin = 1
let g:loaded_netrw = 1 | let g:loaded_netrwPlugin = 1
let g:loaded_tutor_mode_plugin = 1
let g:loaded_vimballPlugin = 1

set autoindent
set autoread
set backupdir=$MYVIMDIR/backup
set belloff=all
set clipboard^=unnamed
set cmdheight=2
set completeopt=fuzzy,menuone,noselect,popup
set diffopt^=vertical,algorithm:histogram
set directory=$MYVIMDIR/swap
set display=lastline
set encoding=utf-8
set expandtab
set fileignorecase
set fillchars=vert:│,fold:─,foldopen:󰍝,foldclose:󰍟,foldsep:│,diff:─,eob:󰜥,lastline:
set formatoptions+=jmM | set formatoptions-=c | set formatoptions-=t
set history=10000
set hlsearch
set ignorecase
set incsearch
set langmenu=none
set nolangremap
set laststatus=2
set lazyredraw
set list
set listchars=tab:󰅂─,leadmultispace:\ │,trail:󱓼,extends:󰄾,precedes:󰄽,conceal:
set nrformats-=octal
set number
set relativenumber
set ruler
set scrolloff=5
set sessionoptions-=help
set shiftwidth=2
set shortmess+=acI
set showcmd
set showfulltag
set showmatch
set sidescrolloff=5
set smartcase
set smartindent
set smarttab
set softtabstop=-1
set spelllang=en,cjk
set spelloptions=camel
set splitbelow
set splitright
set statusline=%<%f\ %m%r%=%{'['.(&fileencoding!=''?&fileencoding:&encoding).']['.&fileformat.']'}%y\ %p\ %l:%v
set noswapfile
set termguicolors
set ttimeout
set ttimeoutlen=100
set undodir=$MYVIMDIR/undo
set undofile
set updatetime=300
set viewdir=$MYVIMDIR/view
set viminfofile=$MYVIMDIR/viminfo
set virtualedit=block
set whichwrap+=<,>,~,[,]
set wildignorecase
set wildmenu
set wildmode=longest:full,full
set wildoptions=fuzzy,pum,tagfile
set nowrap
set nowritebackup

let &showbreak = '󱞪   '

if executable('rg')
  set grepformat=%f:%l:%c:%m
  set grepprg=rg\ --vimgrep
endif

if exists('+macmeta')
  set macmeta
endif

if has('gui_running')
  set guioptions+=chk | set guioptions-=T | set guioptions-=e | set guioptions-=m
endif

if has('vim_starting')
  let &t_SI ..= "\e[6 q"
  let &t_EI ..= "\e[2 q"
  let &t_SR ..= "\e[4 q"
endif

if has('win32')
  set completeslash=slash
  set fileformats=unix,dos
endif

augroup vimrc
  autocmd!
  autocmd BufNewFile,BufRead *.ahk,*.bat,*.cmd,*.ps1,*.reg,*.vb,*.vbs setlocal fileformat=dos fileencoding=cp932 completeslash=backslash
  autocmd BufNewFile,BufRead gitconfig,.gitconfig,*/git/config,*/.git/config setlocal tabstop=4 noexpandtab
  autocmd FileType dbout,fugitive,help,qf nnoremap <silent> <buffer> q :<C-u>quit<CR>
  autocmd FileType html,markdown,txt setlocal spell
augroup END

command! -nargs=* Grep grep <args> | cwindow
command! -nargs=* Vterminal vertical terminal ++close <args>

if executable('tig')
  command! -nargs=* Tig terminal ++close tig <f-args>
endif

let g:mapleader = ','
let g:maplocalleader = ' '

noremap n nzz
noremap N Nzz
noremap Y y$

noremap! <C-a> <Home>
noremap! <C-e> <End>
noremap! <C-d> <Del>
noremap! <C-b> <Left>
noremap! <C-f> <Right>
map! <C-n> <Down>
map! <C-p> <Up>

noremap! ¥ \
noremap! <M-¥> ¥
noremap! <M-\> ¥

nnoremap <C-w>- <C-w>s
nnoremap <C-w>\| <C-w>v
nnoremap <silent> <Esc><Esc> :<C-u>nohlsearch<CR>
nnoremap <silent> <S-Tab> :<C-u>tabprevious<CR>
nnoremap <silent> <Tab> :<C-u>tabnext<CR>
nnoremap <silent> <M-.> :<C-u>if tabpagenr() != tabpagenr('$') \| tabmove +\| endif<CR>
nnoremap <silent> <M-,> :<C-u>if tabpagenr() != 1 \| tabmove -\| endif<CR>

nnoremap [q :<C-u>cprevious<CR>
nnoremap ]q :<C-u>cnext<CR>

if has('win32') && executable('powershell')
  nnoremap <Leader>sh :<C-u>Vterminal powershell<CR>
else
  nnoremap <Leader>sh :<C-u>Vterminal<CR>
endif

function! s:LoadPlugins(timer)
  packadd comment
  packadd! editorconfig
  packadd! matchit
  packadd nohlsearch

  let l:vimplug = expand($MYVIMDIR .. '/autoload/plug.vim')

  if !filereadable(l:vimplug)
    if executable('curl')
      call system('curl -fLo ' .. shellescape(l:vimplug) .. ' --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim')
    endif

    if !filereadable(l:vimplug)
      echoerr 'Please install the vim-plug manually. You can download it from https://github.com/junegunn/vim-plug and put it in ' .. l:vimplug

      finish
    endif
  endif

  if executable('git') && plug#begin('~/.local/vim/plugin')
    " ale
    let g:ale_completion_enabled = 1
    let g:ale_linters = { 'markdown': [ 'textlint' ] }

    " coc.nvim
    let g:coc_data_home = '~/.local/vim/coc'
    let g:coc_global_extensions = [
          \ 'coc-snippets',
          \ 'coc-markdown-preview-enhanced', 'coc-webview',
          \ 'coc-vimlsp',
          \ 'coc-json', 'coc-toml', 'coc-xml', 'coc-yaml',
          \ 'coc-html', 'coc-css',
          \ ]

    if executable('clangd')
      call add(g:coc_global_extensions, 'coc-clangd')
    endif

    if executable('cmake')
      call add(g:coc_global_extensions, 'coc-cmake')
    endif

    if executable('docker')
      call add(g:coc_global_extensions, 'coc-docker')
    endif

    if executable('dotnet')
      call add(g:coc_global_extensions, 'coc-omnisharp')
    endif

    if executable('go')
      call add(g:coc_global_extensions, 'coc-go')
    endif

    if executable('javac')
      call add(g:coc_global_extensions, 'coc-java')
    endif

    if executable('lua') || executable('luajit')
      call add(g:coc_global_extensions, 'coc-lua')
    endif

    if executable('node')
      call extend(g:coc_global_extensions, [
            \ 'coc-tsserver', 'coc-eslint', 'coc-prettier',
            \ 'coc-prisma', '@yaegassy/coc-volar',
            \ ])
    endif

    if executable('perl')
      call add(g:coc_global_extensions, 'coc-perl')
    endif

    if executable('php')
      call extend(g:coc_global_extensions, [
            \ 'coc-phpls', 'coc-phpactor', 'coc-php-cs-fixer', '@yaegassy/coc-phpstan',
            \ '@yaegassy/coc-laravel', 'coc-blade',
            \ ])
    endif

    if executable('python3') || executable('python')
      call extend(g:coc_global_extensions, [ 'coc-pyright', 'coc-pydocstring', ])
    endif

    if executable('ruby')
      call add(g:coc_global_extensions, 'coc-solargraph')
    endif

    if executable('rustc')
      call add(g:coc_global_extensions, 'coc-rust-analyzer')
    endif

    if executable('sqlite3') || executable('psql') || executable('mysql')
      call add(g:coc_global_extensions, 'coc-sql')
    endif

    " dadbod
    let g:db_ui_winwidth = 30
    let g:db_ui_win_position = 'right'
    let g:db_ui_use_nerd_fonts = 1

    " fzf
    let g:fzf_action = { 'Ctrl-t': 'tab split', 'Ctrl-i': 'split', 'Ctrl-s': 'vsplit' }
    let g:fzf_layout = { 'down': '40%' }
    let g:fzf_preview_window = [ 'right,50%', 'Ctrl-/' ]

    " nerdtree
    let g:NERDTreeIgnore = [ '\~$', '\.git$' ]
    let g:NERDTreeQuitOnOpen = 1
    let g:NERDTreeShowHidden = 1
    let g:NERDTreeWinSize = 30

    " tagbar
    let g:tagbar_autofocus = 1
    let g:tagbar_width = 30

    " translate-shell.vim
    let g:trans_advanced_options = '-brief'
    let g:trans_default_direction = ':ja'
    let g:trans_join_lines = 1

    " undotree
    let g:undotree_SetFocusWhenToggle = 1
    let g:undotree_SplitWidth = 30
    let g:undotree_WindowLayout = 3

    " vim-ai
    let g:vim_ai_token_file_path = expand('~/.config/openai.token')
    let g:vim_ai_chat_markdown = 1
    let s:vim_ai_default_prompt =<< trim EOF
you are a general assistant.
answer shortly, consisely and only what you are asked.
do not provide any explanantion or comments if not requested.
if you answer in a code, do not wrap it in markdown code block.
you must answer in japanese.
EOF
    let g:vim_ai_complete = {
          \   'options': {
          \     'model': 'gpt-4o-mini',
          \     'temperature': 0.1,
          \     'stream': 1,
          \     'selection_boundary': '#####',
          \     'initial_prompt': s:vim_ai_default_prompt,
          \   },
          \ }
    let g:vim_ai_edit = {
          \   'options': {
          \     'model': 'gpt-4o-mini',
          \     'temperature': 0.1,
          \     'stream': 1,
          \     'selection_boundary': '#####',
          \     'initial_prompt': s:vim_ai_default_prompt,
          \   },
          \ }
    let g:vim_ai_chat = {
          \   'options': {
          \     'model': 'gpt-4o-mini',
          \     'temperature': 1.0,
          \     'stream': 1,
          \     'initial_prompt': s:vim_ai_default_prompt,
          \   },
          \ }

    " vim-airline
    let g:airline_extensions = [
          \ 'ale',
          \ 'branch',
          \ 'coc',
          \ 'fugitiveline',
          \ 'fzf',
          \ 'obsession',
          \ 'quickfix',
          \ 'scrollbar',
          \ 'tabline',
          \ 'tagbar',
          \ 'term',
          \ 'undotree',
          \ 'whitespace',
          \ ]
    let g:airline_experimental = 1
    let g:airline_powerline_fonts = 1
    let g:airline_left_sep = ''
    let g:airline_right_sep = ''
    let g:airline_left_alt_sep = ''
    let g:airline_right_alt_sep = ''

    if !exists('g:airline_symbols')
      let g:airline_symbols = {}
    endif

    let g:airline_symbols.linenr = ' '
    let g:airline_symbols.maxlinenr = ''
    let g:airline_symbols.colnr = ':'
    let g:airline_symbols.branch = '󰘬'
    let g:airline_symbols.paste = '󰆒 Paste'
    let g:airline_symbols.readonly = '󰑇 Readonly'
    let g:airline_symbols.spell = '󰓆 Spell'
    let g:airline_symbols.crypt = '󰌾 Crypt'
    let g:airline_symbols.dirty = ' 󱐋'
    let g:airline_symbols.notexists = ' 󱥸'
    let g:airline_symbols.whitespace = '󱗽󱞥'

    let g:airline#extensions#ale#error_symbol = '󰅖 Error:'
    let g:airline#extensions#ale#warning_symbol = '󰈅 Warning:'
    let g:airline#extensions#coc#error_symbol = g:airline#extensions#ale#error_symbol
    let g:airline#extensions#coc#warning_symbol = g:airline#extensions#ale#warning_symbol
    let g:airline#extensions#obsession#indicator_text = ' Session'
    let g:airline#extensions#tabline#show_buffers = 0
    let g:airline#extensions#tabline#show_splits = 0

    " vim-buffergator
    let g:buffergator_autoexpand_on_split = 0
    let g:buffergator_autoupdate = 1
    let g:buffergator_suppress_keymaps = 1
    let g:buffergator_vsplit_size = 30

    " vim-devicons
    let g:webdevicons_enable_unite = 0
    let g:webdevicons_enable_vimfiler = 0
    let g:webdevicons_enable_ctrlp = 0
    let g:webdevicons_enable_startify = 0
    let g:webdevicons_enable_flagship_statusline = 0
    let g:webdevicons_enable_denite = 0

    Plug 'airblade/vim-gitgutter'
    Plug 'dhruvasagar/vim-table-mode'
    Plug 'easymotion/vim-easymotion'
    Plug 'github/copilot.vim'
    Plug 'jeetsukumaran/vim-buffergator'
    Plug 'mbbill/undotree'
    Plug 'preservim/nerdtree'
    Plug 'sainnhe/sonokai'
    Plug 'sheerun/vim-polyglot'
    Plug 'tpope/vim-dadbod' | Plug 'kristijanhusak/vim-dadbod-ui' | Plug 'kristijanhusak/vim-dadbod-completion'
    Plug 'tpope/vim-fugitive'
    Plug 'tpope/vim-obsession'
    Plug 'tpope/vim-repeat'
    Plug 'tpope/vim-surround'
    Plug 'vim-jp/vimdoc-ja'

    if executable('ctags')
      Plug 'preservim/tagbar'
    endif

    if executable('fzf')
      Plug 'junegunn/fzf' | Plug 'junegunn/fzf.vim'
    endif

    if executable('node')
      Plug 'dense-analysis/ale'
      Plug 'neoclide/coc.nvim', { 'branch': 'release' } | Plug 'honza/vim-snippets'
    endif

    if executable('trans')
      Plug 'echuraev/translate-shell.vim'
    endif

    if has('python3')
      Plug 'madox2/vim-ai'
    endif

    Plug 'vim-airline/vim-airline'
    Plug 'ryanoasis/vim-devicons'

    call plug#end()

    for key in keys(g:plugs)
      if !isdirectory(expand(g:plugs[key].dir .. '/.git'))
        echomsg 'Please wait for a while to complete the installation.'

        PlugInstall --sync

        break
      endif
    endfor
  endif

  " coc.nvim
  if exists(':CocStart')
    CocStart

    function! s:ShowDocumentation()
      if CocAction('hasProvider', 'hover')
        call CocActionAsync('doHover')
      else
        call feedkeys('K', 'in')
      endif
    endfunction

    inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
          \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

    if has('nvim')
      inoremap <silent><expr> <c-space> coc#refresh()
    else
      inoremap <silent><expr> <c-@> coc#refresh()
    endif

    nmap <silent><nowait> [g <Plug>(coc-diagnostic-prev)
    nmap <silent><nowait> ]g <Plug>(coc-diagnostic-next)

    nmap <silent><nowait> gd <Plug>(coc-definition)
    nmap <silent><nowait> gy <Plug>(coc-type-definition)
    nmap <silent><nowait> gi <Plug>(coc-implementation)
    nmap <silent><nowait> gr <Plug>(coc-references)

    nnoremap <silent> K :call <SID>ShowDocumentation()<CR>

    nmap <leader>rn <Plug>(coc-rename)

    xmap <leader>f  <Plug>(coc-format-selected)
    nmap <leader>f  <Plug>(coc-format-selected)

    xmap <leader>a  <Plug>(coc-codeaction-selected)
    nmap <leader>a  <Plug>(coc-codeaction-selected)

    nmap <leader>ac  <Plug>(coc-codeaction-cursor)
    nmap <leader>as  <Plug>(coc-codeaction-source)
    nmap <leader>qf  <Plug>(coc-fix-current)
    nmap <C-a> <Plug>(coc-codeaction)

    nmap <silent> <leader>re <Plug>(coc-codeaction-refactor)
    xmap <silent> <leader>r  <Plug>(coc-codeaction-refactor-selected)
    nmap <silent> <leader>r  <Plug>(coc-codeaction-refactor-selected)

    nmap <leader>cl  <Plug>(coc-codelens-action)

    xmap if <Plug>(coc-funcobj-i)
    omap if <Plug>(coc-funcobj-i)
    xmap af <Plug>(coc-funcobj-a)
    omap af <Plug>(coc-funcobj-a)
    xmap ic <Plug>(coc-classobj-i)
    omap ic <Plug>(coc-classobj-i)
    xmap ac <Plug>(coc-classobj-a)
    omap ac <Plug>(coc-classobj-a)

    if has('nvim-0.4.0') || has('patch-8.2.0750')
      nnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
      nnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
      inoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : "\<Right>"
      inoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : "\<Left>"
      vnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
      vnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
    endif

    nmap <silent> <C-s> <Plug>(coc-range-select)
    xmap <silent> <C-s> <Plug>(coc-range-select)

    nnoremap <silent><nowait> <LocalLeader>g  :<C-u>CocList diagnostics<cr>
    nnoremap <silent><nowait> <LocalLeader>e  :<C-u>CocList extensions<cr>
    nnoremap <silent><nowait> <LocalLeader>r  :<C-u>CocList commands<cr>
    "nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
    "nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>
    "nnoremap <silent><nowait> <space>j  :<C-u>CocNext<CR>
    "nnoremap <silent><nowait> <space>k  :<C-u>CocPrev<CR>

    let g:coc_snippet_next = '<C-j>'
    let g:coc_snippet_prev = '<C-k>'

    imap <C-l> <Plug>(coc-snippets-expand)
    vmap <C-j> <Plug>(coc-snippets-select)
    imap <C-j> <Plug>(coc-snippets-expand-jump)
    xmap <leader>x  <Plug>(coc-convert-snippet)

    command! -nargs=0 Format :call CocActionAsync('format')
    command! -nargs=? Fold :call CocAction('fold', <f-args>)
    command! -nargs=0 OR :call CocActionAsync('runCommand', 'editor.action.organizeImport')
    command! -nargs=0 OpenPreview CocCommand markdown-preview-enhanced.openPreview

    augroup vimrc
      "autocmd CursorHold * silent call CocActionAsync('highlight')
      autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
    augroup end
  endif

  " dadbod
  if exists(':DBUIToggle')
    function! s:DBUIToggle()
      try
        TagbarClose
      catch
      endtry

      try
        UndotreeHide
      catch
      endtry

      DBUIToggle
    endfunction

    nnoremap <silent> <LocalLeader>d :<C-u>call <SID>DBUIToggle()<CR>
  endif

  " fzf
  if exists(':Files')
    if executable('fd')
      let $FZF_DEFAULT_COMMAND = 'fd --hidden --follow --type f'
    elseif executable('rg')
      let $FZF_DEFAULT_COMMAND = 'rg --hidden --follow --files'
    endif

    nnoremap <silent> <LocalLeader>f :<C-u>Files<CR>
    nnoremap <silent> <LocalLeader>h :<C-u>History<CR>
    nnoremap <silent> <LocalLeader>c :<C-u>History:<CR>
    nnoremap <silent> <LocalLeader>s :<C-u>History/<CR>
    nnoremap <silent> <LocalLeader>w :<C-u>Windows<CR>
  endif

  " nerdtree
  if exists(':NERDTreeToggleVCS')
    function! s:NERDTreeToggleVCS()
      try
        BuffergatorClose
      catch
      endtry

      NERDTreeToggleVCS
    endfunction

    nnoremap <silent> <LocalLeader>n :<C-u>call <SID>NERDTreeToggleVCS()<CR>
  endif

  " sonokai
  let s:colors_name = 'sonokai'
  let g:airline_theme = s:colors_name
  let g:sonokai_diagnostic_text_highlight = 1
  let g:sonokai_diagnostic_line_highlight = 1

  if !empty(getcompletion(s:colors_name, 'color'))
    set background=dark

    execute 'colorscheme ' .. s:colors_name
  endif

  " tagbar
  if exists(':TagbarToggle')
    function! s:TagbarToggle()
      try
        DBUIClose
      catch
      endtry

      try
        UndotreeHide
      catch
      endtry

      TagbarToggle
    endfunction

    nnoremap <silent> <LocalLeader>t :<C-u>call <SID>TagbarToggle()<CR>
  endif

  " undotree
  if exists(':UndotreeToggle')
    function! s:UndotreeToggle()
      try
        DBUIClose
      catch
      endtry

      try
        TagbarClose
      catch
      endtry

      UndotreeToggle
    endfunction

    nnoremap <silent> <LocalLeader>u :<C-u>call <SID>UndotreeToggle()<CR>
  endif

  " vim-buffergator
  if exists(':BuffergatorTabsToggle')
    function! s:BuffergatorToggle()
      try
        NERDTreeClose
      catch
      endtry

      BuffergatorToggle
    endfunction

    nnoremap <silent> <LocalLeader>b :<C-u>call <SID>BuffergatorToggle()<CR>
  endif

  " vim-ai
  if exists(':AIChat')
    augroup vimrc
      autocmd FileType aichat autocmd! nohlsearch
      autocmd FileType aichat xnoremap <leader>g :AIChat<CR>
      autocmd FileType aichat nnoremap <leader>g :AIChat<CR>
      autocmd FileType aichat setlocal wrap
    augroup end

    command! -range -nargs=* AIComment <line1>,<line2>AIChat you are a code assistant. generate block comments for the following code. you must answer in japanese. <args>
    command! -range -nargs=* AIExplain <line1>,<line2>AIChat you are a code assistant. explain the folowing code. you must answer in japanese. <args>
    command! -range -nargs=* AICommit <line1>,<line2>AIChat you are a code assistant. generate commit message for the following changes/code. you must answer in japanese. <args>
    command! -range -nargs=* AIFindBug <line1>,<line2>AIChat you are a code assistant. find bugs and code smells. you must answer in japanese. <args>
    command! -range -nargs=* AIRefactor <line1>,<line2>AIChat you are a code assistant, refactor the folllowing code. <args>
    command! -range -nargs=* AIReview <line1>,<line2>AIChat you are a code assistant. review the following code. you must answer in japanese. <args>
    command! -range -nargs=* AIUnitTest <line1>,<line2>AIChat you are a code assistant. generate unit tests for the following code. <args>
    command! -range -nargs=* AISQL <line1>,<line2>AIChat you are a database administrator. optimize the following sql query. <args>
    command! -range -nargs=* AISummarize <line1>,<line2>AIChat you are a proofreading expert, summarize following document in japanese. <args>

    command! -range -nargs=* AISimplify <line1>,<line2>AIEdit you are a proofreading expert, simplify the following document to make it easier to understand, while keeping the original meaning. <args>
    command! -range -nargs=* AISpell <line1>,<line2>AIEdit you are a proofreading expert. fix grammar and spelling errors. <args>
    command! -range -nargs=* AITransEn <line1>,<line2>AIEdit you are a translator. translate to english. <args>
    command! -range -nargs=* AITransJa <line1>,<line2>AIEdit you are a translator. translate to japanese. <args>
  endif

endfunction

if has('gui_running')
  autocmd vimrc GUIEnter * call timer_start(10, function('s:LoadPlugins'))
else
  call timer_start(10, function('s:LoadPlugins'))
endif
