scriptencoding utf-8

syntax enable

filetype plugin indent on

packadd! matchit

set autoindent
set autoread
set backspace=indent,eol,start
set nobackup
set belloff=all
set clipboard& | set clipboard+=unnamed
set cmdheight=2
set completeopt=menuone,longest,preview
set diffopt& | set diffopt+=vertical,algorithm:histogram
set display=lastline
set encoding=utf-8
set expandtab
set fileignorecase
set formatoptions& | set formatoptions+=jmM | set formatoptions-=c | set formatoptions-=t
set nofoldenable
set history=10000
set hlsearch
set ignorecase
set incsearch
set nolangremap
set langmenu=none
set laststatus=2
set lazyredraw
set list
set listchars=tab:>-,trail:-,extends:>,precedes:<
set nrformats& | set nrformats-=octal
set number
set ruler
set scrolloff=5
set shiftwidth=2
set shortmess& | set shortmess+=acI
set showbreak=>\ 
set showcmd
set showmatch
set sidescrolloff=5
set smartcase
set smartindent
set smarttab
set softtabstop=-1
set nospell | set spelllang=en,cjk
set splitbelow
set splitright
set statusline=%<%f\ %m%r%=%{'['.(&fileencoding!=''?&fileencoding:&encoding).']['.&fileformat.']'}%y\ %p\ %l:%v
set noswapfile
set ttimeout
set ttimeoutlen=100
set noundofile
set updatetime=300
set virtualedit=block
set whichwrap& | set whichwrap+=<,>,~,[,]
set wildignorecase
set wildmenu
set wildmode=longest:full,full
set wildoptions=fuzzy,pum,tagfile
set wrap
set nowritebackup

if executable('rg')
  set grepformat& | set grepformat+=%f:%l:%c:%m
  set grepprg=rg\ --vimgrep
endif

if exists('+macmeta')
  set macmeta
endif

if has('gui_running')
  set guioptions& | set guioptions+=chk | set guioptions-=T | set guioptions-=e | set guioptions-=m
endif

if has('win32')
  set completeslash=slash
  set fileformats=unix,dos
endif

if has('vcon')
  set termguicolors
endif

augroup vimrc
  autocmd!
  autocmd BufNewFile,BufRead *.ahk,*.bat,*.cmd,*.ps1,*.reg,*.vb,*.vbs setlocal fileformat=dos fileencoding=cp932 completeslash=backslash
  autocmd BufNewFile,BufRead gitconfig,.gitconfig,*/git/config,*/.git/config setlocal tabstop=4 noexpandtab
  autocmd FileType dbout,fugitive,help,qf nnoremap <silent> <buffer> q :<C-u>quit<CR>
  autocmd FileType html,markdown,txt setlocal spell
augroup END

command! -nargs=* Grep grep <args> | cwindow

if has('win32')
  command! -nargs=* Vterminal vertical terminal ++close powershell
else
  command! -nargs=* Vterminal vertical terminal ++close
endif

command! -nargs=* Tig terminal ++close tig <f-args>

let g:mapleader = ','
let g:maplocalleader = ' '

noremap j gj
noremap k gk
noremap n nzz
noremap N Nzz
noremap <C-@> <C-]>

cnoremap <C-a> <Home>
cnoremap <C-b> <Left>
cnoremap <C-d> <Del>
cnoremap <C-e> <End>
cnoremap <C-f> <Right>
cnoremap <C-n> <Down>
cnoremap <C-p> <Up>

inoremap <C-a> <Home>
inoremap <C-b> <Left>
inoremap <C-d> <Del>
inoremap <C-e> <End>
inoremap <C-f> <Right>
inoremap <C-n> <Down>
inoremap <C-p> <Up>
inoremap <F15> <Nop>

nnoremap <C-w>- <C-w>s
nnoremap <C-w>\| <C-w>v
nnoremap <silent> <Esc><Esc> :<C-u>nohlsearch<CR>
nnoremap <silent> <S-Tab> :<C-u>tabprevious<CR>
nnoremap <silent> <Tab> :<C-u>tabnext<CR>
nnoremap Y y$
nnoremap [q :<C-u>cprevious<CR>
nnoremap ]q :<C-u>cnext<CR>
nnoremap <silent> <LocalLeader>1 :<C-u>1tabnext<CR>
nnoremap <silent> <LocalLeader>2 :<C-u>2tabnext<CR>
nnoremap <silent> <LocalLeader>3 :<C-u>3tabnext<CR>
nnoremap <silent> <LocalLeader>4 :<C-u>4tabnext<CR>
nnoremap <silent> <LocalLeader>5 :<C-u>5tabnext<CR>
nnoremap <silent> <LocalLeader>6 :<C-u>6tabnext<CR>
nnoremap <silent> <LocalLeader>7 :<C-u>7tabnext<CR>
nnoremap <silent> <LocalLeader>8 :<C-u>8tabnext<CR>
nnoremap <silent> <LocalLeader>9 :<C-u>9tabnext<CR>
nnoremap <silent> <LocalLeader>0 :<C-u>$tabnext<CR>
nnoremap <LocalLeader>h <C-w>h
nnoremap <LocalLeader>j <C-w>j
nnoremap <LocalLeader>k <C-w>k
nnoremap <LocalLeader>l <C-w>l
nnoremap <Leader>sh :<C-u>Vterminal<CR>

call plug#begin()
  Plug 'rafi/awesome-vim-colorschemes'
  Plug 'github/copilot.vim'
  Plug 'editorconfig/editorconfig-vim'
  Plug 'junegunn/fzf' | Plug 'junegunn/fzf.vim'
  Plug 'preservim/nerdcommenter'
  Plug 'preservim/nerdtree' | Plug 'Xuyuanp/nerdtree-git-plugin' | Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
  Plug 'godlygeek/tabular' | Plug 'preservim/vim-markdown'
  Plug 'mbbill/undotree'
  Plug 'jeetsukumaran/vim-buffergator'
  Plug 'easymotion/vim-easymotion'
  Plug 'tpope/vim-fugitive' | Plug 'kazuya-watanabe/gflow.vim'
  Plug 'airblade/vim-gitgutter'
  Plug 'sheerun/vim-polyglot'
  Plug 'tpope/vim-repeat'
  Plug 'honza/vim-snippets'
  Plug 'tpope/vim-surround'
  Plug 'vim-jp/vimdoc-ja'
  Plug 'liuchengxu/vista.vim'
  Plug 'vim-airline/vim-airline' | Plug 'vim-airline/vim-airline-themes' | let g:airline#extensions#tabline#enabled = 1

  if executable('npm')
    Plug 'dense-analysis/ale'
    Plug 'neoclide/coc.nvim', { 'branch': 'release' }
    Plug 'prisma/vim-prisma'
  endif

  if executable('trans')
    Plug 'echuraev/translate-shell.vim'
  endif

  if has('gui_running') || exists('$NERDFONT')
    Plug 'ryanoasis/vim-devicons' | Plug 'adelarsq/vim-devicons-emoji'
  endif
call plug#end()

" ale
let g:ale_completion_enabled = 1
let g:ale_linters = { 'markdown': [ 'textlint' ] }

" awesome-vim-colorsches
let s:colors_name= 'PaperColor'

if len(getcompletion(s:colors_name, 'color'))
  set background=dark

  execute 'colorscheme ' . s:colors_name
endif

" coc.nvim
let g:coc_global_extensions = [
      \ 'coc-highlight', 'coc-snippets',
      \ '@yaegassy/coc-ansible',
      \ 'coc-clangd', 'coc-cmake',
      \ 'coc-docker',
      \ 'coc-go', 'coc-golines',
      \ 'coc-html', 'coc-html-css-support', 'coc-htmlhint', 'coc-class-css', 'coc-css', 'coc-cssmodules', 'coc-stylelint', '@yaegassy/coc-tailwindcss3', 'coc-unocss',
      \ 'coc-java',
      \ 'coc-json', 'coc-toml', 'coc-yaml',
      \ 'coc-markdown-preview-enhanced', 'coc-markdownlint', 'coc-webview',
      \ 'coc-omnisharp',
      \ 'coc-phpls', '@yaegassy/coc-phpstan', 'coc-php-cs-fixer', 'coc-blade', '@yaegassy/coc-laravel',
      \ 'coc-pyright', 'coc-pydocstring', '@yaegassy/coc-ruff', 'coc-htmldjango',
      \ 'coc-rust-analyzer',
      \ 'coc-sh',
      \ 'coc-sql', 'coc-sqlfluff',
      \ 'coc-tsserver', 'coc-eslint', 'coc-prettier', 'coc-angular', '@yaegassy/coc-volar', 'coc-prisma',
      \ 'coc-vimlsp',
      \ ]

command! -nargs=0 OpenPreview CocCommand markdown-preview-enhanced.openPreview

autocmd vimrc CursorHold * call CocActionAsync('highlight')

function! s:ShowDocumentation()
  if CocAction('hasProvider', 'hover')
    call CocActionAsync('definitionHover')
  else
    call feedkeys('K', 'in')
  endif
endfunction

nnoremap <silent> K :<C-u>call <SID>ShowDocumentation()<CR>

inoremap <silent><expr> <C-n> coc#pum#visible() ? coc#pum#next(1) : '<C-n>'
inoremap <silent><expr> <C-p> coc#pum#visible() ? coc#pum#prev(1) : '<C-p>'
inoremap <silent><expr> <Down> coc#pum#visible() ? coc#pum#next(0) : '<Down>'
inoremap <silent><expr> <Up> coc#pum#visible() ? coc#pum#prev(0) : '<Up>'

inoremap <silent><expr> <C-f> coc#pum#visible() ? coc#pum#scroll(1) : '<Right>'
inoremap <silent><expr> <C-b> coc#pum#visible() ? coc#pum#scroll(0) : '<Left>'
inoremap <silent><expr> <PageDown> coc#pum#visible() ? coc#pum#scroll(1) : '<PageDown>'
inoremap <silent><expr> <PageUp> coc#pum#visible() ? coc#pum#scroll(0) : '<PageUp>'

inoremap <silent><expr> <C-e> coc#pum#visible() ? coc#pum#cancel() : '<End>'
inoremap <silent><expr> <C-y> coc#pum#visible() ? coc#pum#confirm() : '<C-y>'
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : '<CR>'
inoremap <silent><expr> <C-@> coc#refresh()

nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
nmap <Leader>rn <Plug>(coc-rename)

xmap <Leader>f <Plug>(coc-format-selected)
nmap <Leader>f <Plug>(coc-format-selected)

xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>ac  <Plug>(coc-codeaction-cursor)
nmap <leader>as  <Plug>(coc-codeaction-source)
nmap <leader>qf  <Plug>(coc-fix-current)

nmap <silent> <leader>re <Plug>(coc-codeaction-refactor)
xmap <silent> <leader>r  <Plug>(coc-codeaction-refactor-selected)
nmap <silent> <leader>r  <Plug>(coc-codeaction-refactor-selected)

nmap <Leader>cl <Plug>(coc-codelens-action)

command! -nargs=? Fold :call CocAction('fold', <f-args>)
command! -nargs=0 Format :call CocActionAsync('format')
command! -nargs=0 OR :call CocActionAsync('runCommand', 'editor.action.organizeImport')

if (get(g:, 'coc_service_initialized', 0) == 0) && exists(':CocStart')
  CocStart
endif

inoremap <C-l> <Plug>(coc-snippets-expand-jump)

let g:coc_snippet_prev = '<C-h>'

" fzf.vim
let g:fzf_action = { 'Ctrl-t': 'tab split', 'Ctrl-i': 'split', 'Ctrl-s': 'vsplit' }
let g:fzf_layout = { 'down': '40%' }
let g:fzf_preview_window = [ 'right,50%', 'Ctrl-/' ]

nnoremap <silent> <Leader>f :<C-u>Files<CR>

" nerdtree
let g:NERDTreeIgnore = ['\~$', '\.sw.$', '\.git$', '\.venv$', 'node_modules$', 'vendor']
let g:NERDTreeWinSize = 30

function! s:NERDTreeToggleVCS()
  try
    BuffergatorClose
  catch
  endtry

  NERDTreeToggleVCS
endfunction

nnoremap <silent> <Leader>e :<C-u>call <SID>NERDTreeToggleVCS()<CR>

" translate-shell.vim
let g:trans_default_direction = ':ja'
let g:trans_advanced_options = '-brief'
let g:trans_join_lines = 1

" undotree
let g:undotree_SetFocusWhenToggle = 1
let g:undotree_SplitWidth = 30
let g:undotree_WindowLayout = 3

function! s:UndotreeToggle()
  try
    Vista!
  catch
  endtry

  UndotreeToggle
endfunction

nnoremap <silent> <Leader>u :<C-u>call <SID>UndotreeToggle()<CR>

" vim-airline
let g:airline_experimental = 1
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline#extensions#tabline#show_buffers = 0
let g:airline#extensions#tabline#show_close_button = 0
let g:airline#extensions#tabline#show_splits = 0
let g:airline#extensions#tabline#show_tab_count = 0

if exists(':AirlineRefresh')
  AirlineRefresh
endif

if has('gui_running')
  let g:airline_theme = g:colors_name

  autocmd vimrc GUIEnter * call airline#switch_matching_theme()
endif

" vim-buffergator
let g:buffergator_autodismiss_on_select = 0
let g:buffergator_autoexpand_on_split = 0
let g:buffergator_autoupdate = 1
let g:buffergator_suppress_keymaps = 1
let g:buffergator_vsplit_size = 30

function! s:BuffergatorToggle()
  try
    NERDTreeClose
  catch
  endtry

  BuffergatorToggle
endfunction

nnoremap <silent> <Leader>b :<C-u>call <SID>BuffergatorToggle()<CR>

" vim-devicons
set fillchars=vert:,fold:,foldopen:,foldclose:,foldsep:,diff:,eob:∙
set listchars=tab:,trail:∙,extends:󰄾,precedes:󰄽
set showbreak=↪∙∙∙

let g:webdevicons_enable = 1
let g:webdevicons_enable_airline_statusline = 1
let g:webdevicons_enable_airline_tabline = 1
let g:webdevicons_enable_nerdtree = 1
let g:webdevicons_conceal_nerdtree_brackets = 1

let g:ale_sign_error = '󰀨'
let g:ale_sign_warning = '󰀦'

if ! get(g:, 'airline_symbols')
  let g:airline_symbols = {}
endif

let g:airline_powerline_fonts = 1
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = '󰘬'
let g:airline_symbols.colnr = ''
let g:airline_symbols.dirty = '󰐗'
let g:airline_symbols.linenr = ''
let g:airline_symbols.maxlinenr = ' '
let g:airline_symbols.notexists = '󰱼'
let g:airline_symbols.paste = '󰆒'
let g:airline_symbols.readonly = '󰌾'
let g:airline_symbols.spell = '󰓆'
let g:airline_symbols.whitespace = '󱁐'
let g:airline#extensions#coc#error_symbol = '󰀩 '
let g:airline#extensions#coc#warning_symbol = '󰀦 '
let g:airline#extensions#tabline#close_symbol = '󰅖'
let g:airline#extensions#tabline#overflow_marker = '…'
let g:airline#extensions#tabline#tabs_label = '󰓩'

let g:NERDTreeDirArrowCollapsible = ''
let g:NERDTreeDirArrowExpandable = ''
let g:NERDTreeGitStatusIndicatorMapCustom = {
      \ 'Modified': '󰧟',
      \ 'Staged': '󰐕',
      \ 'Untracked': '󰓎',
      \ 'Renamed': '󰁔',
      \ 'Unmerged': '󰦎',
      \ 'Deleted': '󰆴',
      \ 'Dirty': '󰂚',
      \ 'Ignored': '󰅖',
      \ 'Clean': '󰄬',
      \ 'Unknown': '?',
      \ }
let g:NERDTreeGitStatusUseNerdFonts = 1

let g:vista_icon_indent = ['└ ', '├ ']
let g:vista_fold_toggle_icons = ['', '']
let g:vista#renderer#icons = {
      \ 'func': '󰊕',
      \ 'function': '󰊕',
      \ 'functions': '󰊕',
      \ 'var': '',
      \ 'variable': '',
      \ 'variables': '',
      \ 'const': '',
      \ 'constant': '',
      \ 'constructor': '󰑶',
      \ 'method': '',
      \ 'package': '',
      \ 'packages': '',
      \ 'enum': '',
      \ 'enummember': '',
      \ 'enumerator': '',
      \ 'module': '',
      \ 'modules': '',
      \ 'type': '',
      \ 'typedef': '',
      \ 'types': '',
      \ 'field': '',
      \ 'fields': '',
      \ 'macro': '󰎤',
      \ 'macros': '󰎤',
      \ 'map': '󰙅',
      \ 'class': '',
      \ 'augroup': '󰙅',
      \ 'struct': '',
      \ 'union': '󰕤',
      \ 'member': '',
      \ 'target': '󰎔',
      \ 'property': '',
      \ 'interface': '',
      \ 'namespace': '',
      \ 'subroutine': '󰒰',
      \ 'implementation': '',
      \ 'typeParameter': '',
      \ 'default': ''
      \ }

call coc#config('suggest.completionItemKindLabels', {
      \ 'keyword': '',
      \ 'variable': '',
      \ 'value': '󰎠',
      \ 'operator': 'ψ',
      \ 'constructor': '󰑶',
      \ 'function': '󰊕',
      \ 'reference': '',
      \ 'constant': '',
      \ 'method': '',
      \ 'struct': '',
      \ 'class': '',
      \ 'interface': '',
      \ 'text': '',
      \ 'enum': '',
      \ 'enumMember': '',
      \ 'module': '',
      \ 'color': '',
      \ 'property': '',
      \ 'field': '',
      \ 'unit': '',
      \ 'event': '󰥕',
      \ 'file': '󰈤',
      \ 'folder': '󰉖',
      \ 'snippet': '󰅩',
      \ 'typeParameter': '',
      \ 'default': ''
      \ })

" vim-markdown
let g:vim_markdown_folding_disabled = 1

" vista.vim
let g:vista_default_executive = 'coc'
let g:vista_sidebar_width = 30

function! s:Vista()
  try
    UndotreeHide
  catch
  endtry

  Vista!!
endfunction

nnoremap <silent> <Leader>t :<C-u>call <SID>Vista()<CR>
