#!/usr/bin/env bash

homebrew_dir="$HOME/.homebrew"

homebrew_uri="https://github.com/Homebrew/brew/tarball/master"

function print_usage() {
    echo "Usage: $0 {install|update|uninstall}" 1>&2
    echo
}

function setup_brew() {
    if [ ! -x "$homebrew_dir/bin/brew" ]
    then
        mkdir -p "$homebrew_dir"
        curl -L "$homebrew_uri" | tar xz --strip 1 -C "$homebrew_dir"
    fi
}

function install_packages() {
    "$homebrew_dir/bin/brew" tap homebrew/cask
    "$homebrew_dir/bin/brew" cask install 1password
    "$homebrew_dir/bin/brew" cask install adguard
    "$homebrew_dir/bin/brew" cask install amazon-music
    "$homebrew_dir/bin/brew" cask install appcleaner
    "$homebrew_dir/bin/brew" cask install cloudmounter
    "$homebrew_dir/bin/brew" cask install docker
    "$homebrew_dir/bin/brew" cask install duet
    "$homebrew_dir/bin/brew" cask install firefox
    "$homebrew_dir/bin/brew" cask install garmin-express
    "$homebrew_dir/bin/brew" cask install google-chrome
    "$homebrew_dir/bin/brew" cask install java
    "$homebrew_dir/bin/brew" cask install macvim
    "$homebrew_dir/bin/brew" cask install steam

    "$homebrew_dir/bin/brew" tap homebrew/cask-drivers
    "$homebrew_dir/bin/brew" cask install xbox360-controller-driver-unofficial

    "$homebrew_dir/bin/brew" tap homebrew/cask-fonts
    "$homebrew_dir/bin/brew" cask install font-inconsolata-nerd-font

    "$homebrew_dir/bin/brew" install cmake
    "$homebrew_dir/bin/brew" install colordiff
    "$homebrew_dir/bin/brew" install composer
    "$homebrew_dir/bin/brew" install ctags
    "$homebrew_dir/bin/brew" install fasd
    "$homebrew_dir/bin/brew" install ffmpeg
    "$homebrew_dir/bin/brew" install fzf
    "$homebrew_dir/bin/brew" install highlight
    "$homebrew_dir/bin/brew" install imagemagick
    "$homebrew_dir/bin/brew" install jq
    "$homebrew_dir/bin/brew" install lesspipe
    "$homebrew_dir/bin/brew" install llvm
    "$homebrew_dir/bin/brew" install npm
    "$homebrew_dir/bin/brew" install p7zip
    "$homebrew_dir/bin/brew" install python
    "$homebrew_dir/bin/brew" install ripgrep
    "$homebrew_dir/bin/brew" install tig
    "$homebrew_dir/bin/brew" install tmux
    "$homebrew_dir/bin/brew" install vim
    "$homebrew_dir/bin/brew" install w3m
    "$homebrew_dir/bin/brew" install wakeonlan
    "$homebrew_dir/bin/brew" install wget
    "$homebrew_dir/bin/brew" install yarn
}

function update_packages() {
    "$homebrew_dir/bin/brew" update
    "$homebrew_dir/bin/brew" upgrade
    "$homebrew_dir/bin/brew" cask upgrade
    "$homebrew_dir/bin/brew" cleanup
}

function uninstall_packages() {
    "$homebrew_dir/bin/brew" cask list | xargs "$homebrew_dir/bin/brew" cask uninstall --force
    "$homebrew_dir/bin/brew" list | xargs "$homebrew_dir/bin/brew" uninstall --force --ignore-dependencies
    "$homebrew_dir/bin/brew" cleanup
    for i in $("$homebrew_dir/bin/brew" tap)
    do
        if [ 'homebrew/core' = $i ]
        then
            continue
        else
            "$homebrew_dir/bin/brew" untap $i
        fi
    done
}

if [ $# -ne 1 ]
then
    print_usage
    exit 1
fi

setup_brew

if [ "$1" = "install" ]
then
    install_packages
elif [ "$1" = "update" ]
then
    update_packages
elif [ "$1" = "uninstall" ]
then
    uninstall_packages
else
    print_usage
    exit 1
fi
