#!/bin/bash

set -eu

test -r $(dirname $0)/subr.sh && source $(dirname $0)/subr.sh

function print_usage() {
    echo "Usage: $0 {install|update}" 1>&2
}

function setup_pip() {
    if ! which curl >/dev/null 2>&1; then
        err 'curl not found.'
        return 1
    fi
    if ! getpython >/dev/null 2>&1; then
        err 'python not found.'
        return 1
    fi
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    $(getpython) get-pip.py --user
    export PATH=$($(getpython) -m site --user-base)/bin:$PATH
    return 0
}

function install_packages() {
    $1 install --user virtualenv
    $1 install --user pyenv
}

function update_packages() {
    $1 list --user --outdated --format=json | jq -r '.[].name' | xargs $1 install --user --upgrade
}

if [ $# -ne 1 ]; then
    print_usage
    exit 1
fi

if type pip3 >/dev/null 2>&1; then
    pipcmd=pip3
elif type pip >/dev/null 2>&1; then
    pipcmd=pip
else setup_pip
    err 'pip command required.'
    exit 1
fi

if ! type jq >/dev/null 2>&1; then
    err 'jq command required.'
    exit 1
fi

if ! type xargs >/dev/null 2>&1; then
    err 'xargs command required.'
    exit 1
fi

if [ "$1" = install ]; then
    install_packages $pipcmd
elif [ "$1" = update ]; then
    update_packages $pipcmd
else
    print_usage
    exit 1
fi
