#!/bin/bash

set -eu

tpmdir=~/.tmux/plugins/tpm

function print_usage() {
    echo "使い方: $0 {install|update}" 1>&2
}

function install_packages() {
    $1/bin/install_plugins
}

function update_packages() {
    $1/bin/update_plugins all
}

if [ $# -ne 1 ]; then
    print_usage
    exit 1
fi

if ! type tmux >/dev/null 2>&1; then
    echo 'tmux コマンドが見つかりません。'
    exit 2
fi

if ! type git >/dev/null 2>&1; then
    echo 'git コマンドが見つかりません。'
    exit 2
fi

if [ ! -d $tpmdir ]; then
    git clone https://github.com/tmux-plugins/tpm.git $tpmdir
fi

if [ "$1" = install ]; then
    install_packages $tpmdir
elif [ "$1" = update ]; then
    update_packages $tpmdir
else
    print_usage
    exit 1
fi
