#!/bin/bash

set -eu

test -r $(dirname $0)/subr.sh && source $(dirname $0)/subr.sh

function print_usage() {
    echo "Usage: $0 {install|update|uninstall}" 1>&2
}

function install_packages() {
    sudo apt update
    sudo apt install colordiff \
        universal-ctags \
        fasd \
        fzf \
        golang \
        highlight \
        jq \
        npm \
        p7zip \
        ripgrep \
        tig \
        tmux \
        w3m \
        wget \
        yarnpkg \
        zplug \
        zsh
}

function update_packages() {
    sudo apt update
    sudo apt full-upgrade
}

function uninstall_packages() {
    sudo apt autoremove colordiff \
        universal-ctags \
        fasd \
        fzf \
        golang \
        highlight \
        jq \
        npm \
        p7zip \
        ripgrep \
        tig \
        tmux \
        w3m \
        wget \
        yarnpkg \
        zplug \
        zsh
}

if [ $# -ne 1 ]; then
    print_usage
    exit 1
fi

if [ "$1" = install ]; then
    install_packages
elif [ "$1" = update ]; then
    update_packages
elif [ "$1" = uninstall ]; then
    uninstall_packages
else
    print_usage
    exit 1
fi
